### ISSUE TITLE
building error!

### ISSUE THREAD

**Issue by nawuxicaa** [nmwsharp/vector-heat-demo#1]
Thank you very much for the great work!

I tried to build it, but I got an error message. Maybe you can help me to solve the problem.

[ 72%] Built target polyscope
[ 73%] Building CXX object deps/geometry-central/src/CMakeFiles/geometry-central.dir/surface/trace_geodesic.cpp.o
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/surface/ply_halfedge_mesh_data.cpp: In member function ‘geometrycentral::surface::VertexData<geometrycentral::Vector3> geometrycentral::surface::PlyHalfedgeMeshData::getVertexColors()’:
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/surface/ply_halfedge_mesh_data.cpp:97:31: error: catching polymorphic type ‘class std::runtime_error’ by value [-Werror=catch-value=]
   97 |   } catch (std::runtime_error orig_e) {
      |                               ^~~~~~
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/surface/ply_halfedge_mesh_data.cpp:110:33: error: catching polymorphic type ‘class std::runtime_error’ by value [-Werror=catch-value=]
  110 |     } catch (std::runtime_error second_e) {
      |                                 ^~~~~~~~
In file included from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/deps/downloads/EIGEN3-src/Eigen/Core:461,
                 from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/deps/downloads/EIGEN3-src/Eigen/SparseCore:11,
                 from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/../include/geometrycentral/utilities/dependent_quantity.h:5,
                 from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/../include/geometrycentral/surface/halfedge_containers.h:4,
                 from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/../include/geometrycentral/surface/halfedge_mesh.h:3,
                 from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/../include/geometrycentral/surface/heat_method_distance.h:7,
                 from /home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/surface/heat_method_distance.cpp:1:
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/deps/downloads/EIGEN3-src/Eigen/src/Core/CwiseBinaryOp.h: In instantiation of ‘Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::CwiseBinaryOp(const Lhs&, const Rhs&, const BinaryOp&) [with BinaryOp = Eigen::internal::scalar_sum_op<double, double>; LhsType = const Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 1> >; RhsType = const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Array<double, -1, 1> >; Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Lhs = Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 1> >; Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Rhs = Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Array<double, -1, 1> >]’:
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/deps/downloads/EIGEN3-src/Eigen/src/Core/../plugins/ArrayCwiseBinaryOps.h:215:1:   required from ‘typename Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::promote_scalar_arg<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::scalar_sum_op<typename Eigen::internal::traits<T>::Scalar, T> > >::value>::type>, const Derived, const typename Eigen::internal::plain_constant_type<Derived, typename Eigen::internal::promote_scalar_arg<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::scalar_sum_op<typename Eigen::internal::traits<T>::Scalar, T> > >::value>::type>::type> >::type Eigen::ArrayBase<Derived>::operator+(const T&) const [with T = double; Derived = Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 1> >; typename Eigen::internal::enable_if<true, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::promote_scalar_arg<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::scalar_sum_op<typename Eigen::internal::traits<T>::Scalar, T> > >::value>::type>, const Derived, const typename Eigen::internal::plain_constant_type<Derived, typename Eigen::internal::promote_scalar_arg<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<typename Eigen::internal::traits<T>::Scalar, T, Eigen::internal::scalar_sum_op<typename Eigen::internal::traits<T>::Scalar, T> > >::value>::type>::type> >::type = const Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<double, double>, const Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 1> >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Array<double, -1, 1> > >]’
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/src/surface/heat_method_distance.cpp:159:31:   required from here
/home/nawuxicaa/vector-heat-demo/deps/geometry-central/deps/downloads/EIGEN3-src/Eigen/src/Core/CwiseBinaryOp.h:105:49: error: implicitly-declared ‘constexpr Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 1> >::ArrayWrapper(const Eigen::ArrayWrapper<Eigen::Matrix<double, -1, 1> >&)’ is deprecated [-Werror=deprecated-copy]
  105 |       : m_lhs(aLhs), m_rhs(aRhs), m_functor(func)

**Comment by nawuxicaa** [comment]
The problem above was solved!
Now  I have other problem with **main.cpp**
Maybe you can help me!Thanks!

[ 98%] Building CXX object CMakeFiles/vector_heat.dir/src/main.cpp.o
/home/nawuxicaa/vector-heat-demo/src/main.cpp: In function ‘int main(int, char**)’:
/home/nawuxicaa/vector-heat-demo/src/main.cpp:389:18: error: catching polymorphic type ‘class args::Help’ by value [-Werror=catch-value=]
  389 |   } catch (args::Help) {
      |                  ^~~~
/home/nawuxicaa/vector-heat-demo/src/main.cpp:392:29: error: catching polymorphic type ‘class args::ParseError’ by value [-Werror=catch-value=]
  392 |   } catch (args::ParseError e) {
      |                             ^

**Comment by nmwsharp** [comment]
Hi @nawuxicaa, pardon the slow response here! I missed the issue initially.

This should now be fixed in the master branch. Please let me know if you still see any problems! (and feel free to reopen the issue).
